# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: espe202451
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ProyectoAplicacionesDistribuidas

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    JWT_KEY: "haJSHdjksh!!1i27@askjdhm2nasa21"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:692859937629:table/InventarioPeliculas
        - arn:aws:dynamodb:us-east-1:692859937629:table/Usuarios

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createPeli:
    handler: src/agregarPeli.agregarPeli
    events:
      - httpApi:
          path: /pelicula
          method: post
  getPeliTable:
    handler: src/obtenerTodo.obtenerTodo
    events:
      - httpApi:
          path: /pelicula
          method: get
  getPeli:
    handler: src/obtenerPeli.obtenerPeli
    events:
      - httpApi:
          path: /pelicula/{id}
          method: get
  updatePeli:
    handler: src/actualizarPeli.actualizarPeli
    events:
      - httpApi:
          path: /pelicula/{id}
          method: put
  deletePeli:
    handler: src/borrarPeli.borrarPeli
    events:
      - httpApi:
          path: /pelicula/{id}
          method: delete
  # Autentificación (login)
  registrarUsuario:
    handler: src/registrarUsuario.registrarUsuario
    events:
      - httpApi:
          path: /usuario/registrar
          method: post
  loginUsuario:
    handler: src/loginUsuario.loginUsuario
    events:
      - httpApi:
          path: /usuario/login
          method: post

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InventarioPeliculas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Usuarios
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
